In [ ]:
# 実践課題 vol.1
AI_STANDARD 機械学習講座vol.1~ vol.5の学習のアウトプットとして、実践的な課題を解いて行きましょう。kaggleというデータサイエンスのコンペティションサイトにある、住宅価格予測のデータを使用した課題です。


![](https://s3-ap-northeast-1.amazonaws.com/ai-std/kadai1-1.png)

[kaggle: House Prices Competition link](https://www.kaggle.com/c/house-prices-advanced-regression-techniques)

## データのダウンロード
２つのデータをダウンロードして、jupyterを起動しているディレクトリに保存して下さい(右クリックでダウンロードを選択できます)。

 - <a href="https://s3-ap-northeast-1.amazonaws.com/ai-std/house_price.csv" download="house_price.csv">前処理済みデータ</a>
 - <a href="https://s3-ap-northeast-1.amazonaws.com/ai-std/y.csv" download="y.csv">正解データ</a>
 
 ![](https://s3-ap-northeast-1.amazonaws.com/ai-std/kadai1-2.png)

In [5]:
# モジュールのインポート

import pandas as pd
import numpy as  np
import seaborn as sns
import matplotlib.pyplot as plt
% matplotlib inline

data = pd.read_csv('house_price.csv')
y = pd.read_csv('y.csv')

### 問題１：dataの上から20行を表示してください。

In [6]:
data.head(20)

LotFrontage   LotArea    Street  LotShape  Utilities  LandSlope  \
0            65  9.042040  1.098612  1.609438   1.609438   1.386294   
1            80  9.169623  1.098612  1.609438   1.609438   1.386294   
2            68  9.328212  1.098612  1.386294   1.609438   1.386294   
3            60  9.164401  1.098612  1.386294   1.609438   1.386294   
4            84  9.565284  1.098612  1.386294   1.609438   1.386294   
5            85  9.555064  1.098612  1.386294   1.609438   1.386294   
6            75  9.218804  1.098612  1.609438   1.609438   1.386294   
7             0  9.247925  1.098612  1.386294   1.609438   1.386294   
8            51  8.719481  1.098612  1.609438   1.609438   1.386294   
9            50  8.912069  1.098612  1.609438   1.609438   1.386294   
10           70  9.323758  1.098612  1.609438   1.609438   1.386294   
11           85  9.386392  1.098612  1.386294   1.609438   1.386294   
12            0  9.470317  1.098612  1.098612   1.609438   1.386294   
13           91  9.273597  1.098612  1.386294   1.609438   1.386294   
14            0  9.298443  1.098612  1.386294   1.609438   1.386294   
15           51  8.719481  1.098612  1.609438   1.609438   1.386294   
16            0  9.327412  1.098612  1.386294   1.609438   1.386294   
17           72  9.286560  1.098612  1.609438   1.609438   1.386294   
18           66  9.524859  1.098612  1.609438   1.609438   1.386294   
19           70  8.930759  1.098612  1.609438   1.609438   1.386294   

    OverallQual  OverallCond  YearBuilt  YearRemodAdd          ...            \
0             7     1.791759   7.602900      7.602900          ...             
1             6     2.197225   7.589336      7.589336          ...             
2             7     1.791759   7.601902      7.602401          ...             
3             7     1.791759   7.557995      7.586296          ...             
4             8     1.791759   7.601402      7.601402          ...             
5             5     1.791759   7.597898      7.598900          ...             
6             8     1.791759   7.603399      7.603898          ...             
7             7     1.945910   7.587817      7.587817          ...             
8             7     1.791759   7.566311      7.576097          ...             
9             5     1.945910   7.570443      7.576097          ...             
10            5     1.791759   7.583756      7.583756          ...             
11            9     1.791759   7.603898      7.604396          ...             
12            5     1.945910   7.582229      7.582229          ...             
13            7     1.791759   7.604396      7.604894          ...             
14            6     1.791759   7.581210      7.581210          ...             
15            7     2.197225   7.565275      7.601902          ...             
16            6     2.079442   7.586296      7.586296          ...             
17            4     1.791759   7.584773      7.584773          ...             
18            5     1.791759   7.603399      7.603399          ...             
19            5     1.945910   7.580189      7.583756          ...             

    SaleType_ConLw  SaleType_New  SaleType_Oth  SaleType_WD  \
0                0             0             0            1   
1                0             0             0            1   
2                0             0             0            1   
3                0             0             0            1   
4                0             0             0            1   
5                0             0             0            1   
6                0             0             0            1   
7                0             0             0            1   
8                0             0             0            1   
9                0             0             0            1   
10               0             0             0            1   
11               0             1             0            0   
12          

### 問題２：ホールド・アウト法によるデータの分割をしてください。
条件：テストデータの割合は3割、random_stateは0、変数は「X_train, X_test, y_train, y_test」を使用

In [188]:
X = df.loc[:,['OverallQual','GrLivArea', 'TotalBsmtSF']].values
y = df.loc[:, ['y']].values
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.3, random_state = 0)

### 問題３：線形回帰モデルを作成してください。
 - モジュールのインポート
 - インスタンスの生成
 - モデルへのfit
 - scoreの表示

In [189]:
from sklearn.linear_model import LinearRegression
lr = LinearRegression()
lr.fit(X_train, y_train)

LinearRegression(copy_X=True, fit_intercept=True, n_jobs=1, normalize=False)

In [206]:
lr.intercept_

array([-664068.56332578])

In [207]:
lr.coef_

array([[ 31288.26463896,  85645.66201187,   4655.35608697]])

In [208]:
def adjusted(score, n_sample, n_features):
    adjusted_score = 1 - (1 - score) * ((n_sample - 1) / (n_sample - n_features - 1))
    return adjusted_score
print('adjusted R^2')
print('train: %3f' % adjusted(lr.score(X_train, y_train), len(y_train), 2))
print('test : %3f' % adjusted(lr.score(X_test, y_test), len(y_test), 2))

adjusted R^2
train: 0.703409
test : 0.687401


### 問題４：Ridge回帰モデルを作成してください。
 - モジュールのインポート
 - インスタンスの生成（引数：alpha=10）
 - モデルへのfit
 - テストデータでのscoreの表示

In [197]:
from sklearn.linear_model import Ridge                       
model_ridge = Ridge(alpha=10)                               
model_ridge.fit(X_train, y_train)                                     

Ridge(alpha=10, copy_X=True, fit_intercept=True, max_iter=None,
   normalize=False, random_state=None, solver='auto', tol=0.001)

In [203]:
model_ridge.coef_

array([[ 32540.71385793,  75842.16413411,   4692.47605843]])

In [204]:
model_ridge.intercept_

array([-600626.41732774])

In [224]:
def adjusted(score, n_sample, n_features):
    adjusted_score = 1 - (1 - score) * ((n_sample - 1) / (n_sample - n_features - 1))
    return adjusted_score
print('adjusted R^2')
print('train: %3f' % adjusted(model_ridge.score(X_train, y_train), len(y_train), 2))
print('test : %3f' % adjusted(model_ridge.score(X_test, y_test), len(y_test), 2))

adjusted R^2
train: 0.702280
test : 0.690026


### 問題５：LASSOモデルを作成してください。
 - モジュールのインポート
 - インスタンスの生成（引数：alpha=200）
 - モデルへのfit
 - テストデータでのscoreの表示

In [225]:
from sklearn.linear_model import Lasso
model_lasso = Lasso(alpha=200)
model_lasso.fit(X_train, y_train) 

Lasso(alpha=200, copy_X=True, fit_intercept=True, max_iter=1000,
   normalize=False, positive=False, precompute=False, random_state=None,
   selection='cyclic', tol=0.0001, warm_start=False)

In [226]:
model_lasso.coef_

array([ 31571.09372202,  83235.85782363,   4520.29070629])

In [227]:
model_lasso.intercept_

array([-647346.29880643])

In [228]:
def adjusted(score, n_sample, n_features):
    adjusted_score = 1 - (1 - score) * ((n_sample - 1) / (n_sample - n_features - 1))
    return adjusted_score
print('adjusted R^2')
print('train: %3f' % adjusted(model_lasso.score(X_train, y_train), len(y_train), 2))
print('test : %3f' % adjusted(model_lasso.score(X_test, y_test), len(y_test), 2))

adjusted R^2
train: 0.703334
test : 0.688247


### 問題６：Elastic Netモデルを作成してください。
 - モジュールのインポート
 - インスタンスの生成（引数：alpha=0.1, l1_ratio=0.9）
 - モデルへのfit
 - scoreの表示

In [229]:
from sklearn.linear_model import ElasticNet                 # ElasticNetのクラスを読み込み
model_en= ElasticNet(alpha=0.1, l1_ratio=0.9)              # ElasticNetのインスタンスを生成
model_en.fit(X_train, y_train)     

ElasticNet(alpha=0.1, copy_X=True, fit_intercept=True, l1_ratio=0.9,
      max_iter=1000, normalize=False, positive=False, precompute=False,
      random_state=None, selection='cyclic', tol=0.0001, warm_start=False)

In [230]:
model_en.coef_

array([ 32564.33231825,  75652.50176802,   4693.27073223])

In [231]:
model_en.intercept_

array([-599395.83803305])

In [232]:
def adjusted(score, n_sample, n_features):
    adjusted_score = 1 - (1 - score) * ((n_sample - 1) / (n_sample - n_features - 1))
    return adjusted_score
print('adjusted R^2')
print('train: %3f' % adjusted(model_en.score(X_train, y_train), len(y_train), 2))
print('test : %3f' % adjusted(model_en.score(X_test, y_test), len(y_test), 2))

adjusted R^2
train: 0.702235
test : 0.690058
